on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/kmods
  IMAGE_TAG: 40

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install buildah -y
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ostree-kmods
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          containerfiles: |
            ./Containerfile
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository_owner }}
      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.4.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
